### ISSUE TITLE
Do not inspect `NODE_ENV`

### ISSUE THREAD

**Issue by jsumners** [jacobbuck/parse-formatted-number#5]
https://github.com/jacobbuck/parse-formatted-number/blob/acde934d4193ff28f12b893b87b1cf584cad7247/src/index.js#L2

Please do not do this. It introduces unexpected behavior due to a hidden environment variable.

**Comment by aliebuck** [comment]
Hi there, thanks for the issue.

For context, this block of code is for type checking the arguments passed to make debugging easier, and the `process.env.NODE_ENV !== 'production'` check ensures this only happens during development. 

This use of `process.env.NODE_ENV` for debugging is pretty common in a lot of JavaScript applications (including [React](https://reactjs.org)) and it's also common for tooling to support it out of the box.

**Comment by jsumners** [comment]
> the process.env.NODE_ENV !== 'production' check ensures this only happens during development.

It really doesn't.
